
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { Toaster } from "sonner";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({subsets: ['latin']});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className}`}
      >
      <Header/>
      <main className="min-h-screen">
      {children}
      </main>
      <Toaster richColors />
        <footer className="bg-muted/50 py-12">
        <div className="container mx-auto px-4 text-center">
  <p className="text-transparent bg-clip-text bg-gradient-to-r from-yellow-400 via-yellow-300 to-yellow-200">
    Made with ❤ by Zehra Kazmi
  </p>
</div>

        </footer>
      </body>
    </html>
    </ClerkProvider>
  );
}
